### ISSUE TITLE
Links between objects 

### ISSUE THREAD

**Issue by Hartorn** [thc-tools/model-schemas#3]
I feel like links between objects, like fields and domains are a good thing, and I would enforce that

I feel like adding a domain inside a field may be bad practice, and confusing (how to handle several field with same domain defined in it)

Also, I would say name and uid should be only one thing. I think this is confusing, and in most cases it would be the same value. 

Finally, I would enforce uid with a pattern authorizing only A-Z, a-z, 0-9 and - _

What do you think?

**Comment by bushi-go** [comment]
I agree on the link part, which get me to the following question : how to ensure that we can uniquely identify a given object, to be able to reference it properly ?

This is partly why I am not sure name and uid would be the same thing. The reason is we may have several databases, which could define entities with the same name (user for example). During processing, we will want to have a way to distinguish between thoses entities, hence, a generated, technical uid seems a good approach to me.

This example might not be the best, my point being : i think we need an identifier that would make us able to identify uniquely each object of our model, to be able to etablish link with other objects.

I am specificaly thinking about how we can link our data model to the metadata/positionning data that we will use to render our model in the yet-to-come Model design IDE. 

I agree that the uid part should bear more constraint, i'm in the process of defining such constraint (one of which, uniqueness, will be a bit tricky to implement within the schema)

**Comment by Hartorn** [comment]
Yeah, good point, let's keep both.
Maybe uid should be mandatory then

**Comment by Hartorn** [comment]
Not sure it is possible to ensure unicity, with this. Guess it should be another validation, external to schema

**Comment by aikigo** [comment]
On this subject, i propose we use guid as defined in the rfc4122, it should allow us to ensure unicity (with high probability).
I feel like it is convenient for our use case, we will have convenient constraint

**Comment by Hartorn** [comment]
OK for uuid or guid

For collection, not useful and not practical : does not mean that you cannot reuse uid in entity instead of domain, does it?

Plus it would make schema not readable and kind of messy I think

**Comment by aikigo** [comment]
What i meant was to have one collection, at the same hierarchical level as the databases collections, which would be one array holding all the guid of the schemas, make validable the unicity of the guid ^^

**Comment by Hartorn** [comment]
I really think unicity should be enforced, but not with schema. It should be written as in some rfc.

Better to keep it simple I think
